controller:
  args:
  - --metrics-bind-address=:8443
  - --leader-elect
  - --health-probe-bind-address=:8081
  env: []
  containerSecurityContext:
    runAsUser: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  image:
    repository: ghcr.io/rancher-sandbox/network-enforcer/controller
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
  tolerations: []
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  affinity: {}

kubernetesClusterDomain: cluster.local
imagePullSecrets: []

obi:
  enabled: true
  preset: network
  config:
    create: false
    name: network-enforcer-obi-config

cniwatcher:
  enabled: true
  # Valid values: aws-vpc, calico, cilium, flannel
  cniType: calico
  image:
    repository: ghcr.io/rancher-sandbox/network-enforcer/cniwatcher
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  # Empty string uses {{ release-name }}-otlp.{{ namespace }}.svc.cluster.local:4317
  otelEndpoint: ""
  calico:
    namespace: calico-system
    goldmaneEndpoint: goldmane.calico-system.svc:7443
  cilium:
    namespace: kube-system
    hubbleEndpoint: unix:///var/run/cilium/hubble.sock
  flannel:
    namespace: kube-system
  "aws-vpc":
    namespace: kube-system
  serviceAccount:
    annotations: {}
