---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.security.rancher.io
  resources:
  - networkpolicyproposals
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.security.rancher.io
  resources:
  - networkpolicyproposals/status
  verbs:
  - get
  - patch
  - update
