{{- if .Values.cniwatcher.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "network-enforcer.fullname" . }}-cniwatcher
  namespace: {{ include "network-enforcer.cniwatcher.namespace" . }}
  labels:
    {{- include "network-enforcer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.cniwatcher.serviceAccount.annotations | nindent 4 }}
{{- end }}
