apiVersion: security.security.rancher.io/v1alpha1
kind: NetworkPolicyProposal
metadata:
  labels:
    app.kubernetes.io/name: network-enforcer
    app.kubernetes.io/managed-by: kustomize
  name: deployment-nginx
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
