{{- if .Values.obi.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-enforcer-obi-config
  labels:
  {{- include "network-enforcer.labels" . | nindent 4 }}
data:
  ebpf-instrument-config.yml: |
    otel_metrics_export:
      endpoint: http://{{ include "network-enforcer.fullname" . }}-otlp:4317
    otel_traces_export:
      endpoint: ""
    attributes:
      kubernetes:
        enable: true
      select:
        obi_network_flow_bytes:
          include: ["*"]
    metrics:
      features:
        - network
{{- end }}
