name: Update helm charts
on:
  workflow_call:
jobs:
  update-network-enforcer-charts:
    name: Update NetworkEnforcer charts
    runs-on: ubuntu-latest
    permissions:
      contents: write # for updatecli to update the repository
      pull-requests: write # for updatecli to create a PR
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@5dfc616e57b07d2302c3f37e5b72a4ead82dbbf8 # v3.4.0

      - name: Update NetworkEnforcer charts
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: "updatecli compose apply --file updatecli/updatecli-compose.release.yaml"
